export const CONFIG = {
    // WALLET_ADDRESS: 'THANKYOUJE4LVRECDJOBPYZXFEVOXF3VQ6QEAXB3BFZWXDFJWE27URFZ3Q',
    WALLET_ADDRESS: 'MTGLPLANYNVD4OMZUQDIZ62G5LRX3JCC2H33VZNYY5VDWLEYW5JRZ3W3GQ',
    TOKEN_ID: 419000,
    APIS: {
      VOI_NODE: 'https://mainnet-api.voi.nodely.dev',
      NAUTILUS_INDEXER: 'https://mainnet-idx.nautilus.sh/nft-indexer/v1'
    }
  } as const